### ISSUE TITLE
Joining channels fails with Konversation

### ISSUE THREAD

**Issue by mmuehlenhoff** [paravoid/ircstream#1]
The first ircstream deployment is up and running at ircstream.wikimedia.org, great work!

With irssi everything seems fine in first tests compared to the legacy setup, but with Konversation 22.12.3 as found in Debian Bookworm/testing/sid joining channels fails. This has been my current go-to test with the legacy infrastructure after e.g. reboots, I have no idea if that is an issue bots might also run into or merely limited to Konversation?

Steps to reproduce:
File -> Quick Connect
Server host: irc1003.wikimedia.org, Port 6667, no "Password", no "Use SSL" and then click "Connect"

Running "/list" in the server status will show the correctly populated channel list, but if I right-click on e.g. "#de.wikipedia" and select "Join Channel" no channel is joined and in the server status I can see the error

> [Error] ##de.wikipedia: No such channel

(With a surplus # in the channel name, not a typo)

**Comment by paravoid** [comment]
I've verified that the fix for #2 addresses this issue as well. This is likely a bug in Konversation? Closing, at least for the time being.
